public class DemoTraining {

    Public Integer addition(Integer firstValue, Integer secondValue ){
        Integer Output;
        Output = firstValue + secondValue;
        system.debug('subramani'+Output);
      return Output;
    }
    
    Public Integer subtraction(Integer firstValue, Integer secondValue ){
        Integer Output;
        Output = firstValue - secondValue;
        system.debug('subramani'+Output);
      return Output;
    }
}